# fichier: nationalities.py

# Dictionnaire de conversion country -> nationalité
country_to_nationality = {
    "Kashyyyk": "Kashyien",
    "Kamino": "Kaminien",
    "France": "Française",
    "Madagascar": "Malgache",
    "USA": "Américaine",
    "Germany": "Allemande",
    "Japan": "Japonaise",
    "United Kingdom": "Britannique",
    "Italy": "Italienne",
    "Spain": "Espagnole",
    "Portugal": "Portugaise",
    "China": "Chinoise",
    "India": "Indienne",
    "Brazil": "Brésilienne",
    "Argentina": "Argentine",
    "Russia": "Russe",
    "Australia": "Australienne",
    "Canada": "Canadienne",
    "Egypt": "Égyptienne",
    "South Africa": "Sud-Africaine",
    "New Zealand": "Néo-Zélandaise",
    "Norway": "Norvégienne",
    "Sweden": "Suédoise",
    "Finland": "Finlandaise",
    "Denmark": "Danoise",
    "Netherlands": "Néerlandaise",
    "Belgium": "Belge",
    "Switzerland": "Suisse",
    "Austria": "Autrichienne",
    "Poland": "Polonaise",
    "Czech Republic": "Tchèque",
    "Slovakia": "Slovaque",
    "Hungary": "Hongroise",
    "Greece": "Grecque",
    "Turkey": "Turque",
    "Korea": "Coréenne",
    "North Korea": "Nord-Coréenne",
    "South Korea": "Sud-Coréenne"
}
